---
is_validator: true
validator_stake_amount: 100000

secp_private_key: "{{ vault_secp_private_key | default('') }}"
bls_private_key: "{{ vault_bls_private_key | default('') }}"
beneficiary_address: "{{ vault_beneficiary_address | default('') }}"
auth_address: "{{ vault_auth_address | default('') }}"
