---
- name: Create loop image
  ansible.builtin.command:
    cmd: "truncate -s {{ triedb_loop_config.image_size }} {{ triedb_loop_config.image_file }}"
    creates: "{{ triedb_loop_config.image_file }}"

- name: Install triedb-loop systemd service
  ansible.builtin.template:
    src: triedb-loop.service.j2
    dest: /etc/systemd/system/triedb-loop.service
    owner: root
    group: root
    mode: "0644"

- name: Enable and start triedb-loop service
  ansible.builtin.systemd:
    name: triedb-loop
    enabled: yes
    state: started
    daemon_reload: yes
