---
- name: Setup Observability Stack
  hosts: validators:fullnodes
  become: yes
  gather_facts: yes

  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
    - ../group_vars/{{ env }}.yml

  roles:
    - role: observability
      tags: [observability]
